"""Shared data models for portfolio monitoring agents."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Literal, Mapping
from uuid import uuid4

from src.config import Settings, get_settings
from src.reports.history import ReportHistoryEntry


AgentResultStatus = Literal["success", "partial", "failed"]
AgentSourceType = Literal["report", "dataset", "web", "manual", "derived"]
AgentArtifactType = Literal["markdown", "json", "table", "recommendation", "text"]


@dataclass(frozen=True)
class AgentInputRef:
    """Reference to an input artifact available to one agent run."""

    key: str
    label: str
    location: str
    source_type: AgentSourceType
    as_of_date: date | None = None
    generated_at: datetime | None = None
    description: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentSource:
    """Traceable source cited by agent findings or summaries."""

    source_type: AgentSourceType
    label: str
    location: str
    retrieved_at: datetime
    effective_date: date | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentArtifact:
    """Materialized output generated by one agent run."""

    artifact_type: AgentArtifactType
    title: str
    content: str | None = None
    path: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentFinding:
    """Single structured finding produced by one agent."""

    title: str
    detail: str
    category: str = "general"
    severity: str = "info"
    asset_id: str | None = None
    tags: tuple[str, ...] = ()
    sources: tuple[AgentSource, ...] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentContext:
    """Common execution context shared by all project agents."""

    agent_name: str
    run_id: str
    as_of_date: date
    generated_at: datetime
    base_currency: str
    settings: Settings
    input_refs: tuple[AgentInputRef, ...] = ()
    report_history: tuple[ReportHistoryEntry, ...] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def available_input_keys(self) -> tuple[str, ...]:
        return tuple(input_ref.key for input_ref in self.input_refs)

    def has_input(self, key: str) -> bool:
        return any(input_ref.key == key for input_ref in self.input_refs)

    def get_input(self, key: str) -> AgentInputRef:
        for input_ref in self.input_refs:
            if input_ref.key == key:
                return input_ref
        raise KeyError(f"Unknown agent input reference: {key}")

    def latest_report(self, report_type: str) -> ReportHistoryEntry | None:
        matching = [entry for entry in self.report_history if entry.report_type == report_type]
        if not matching:
            return None
        return sorted(matching, key=lambda entry: (entry.generated_at, entry.report_id), reverse=True)[0]


@dataclass(frozen=True)
class AgentRequest:
    """Flexible request contract for one agent execution."""

    scope: Mapping[str, Any] = field(default_factory=dict)
    parameters: Mapping[str, Any] = field(default_factory=dict)
    constraints: Mapping[str, Any] = field(default_factory=dict)
    input_refs: tuple[str, ...] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentResult:
    """Structured output returned by every project agent."""

    status: AgentResultStatus
    summary: str
    findings: tuple[AgentFinding, ...] = ()
    artifacts: tuple[AgentArtifact, ...] = ()
    sources: tuple[AgentSource, ...] = ()
    warnings: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def is_success(self) -> bool:
        return self.status == "success"

    @property
    def is_failure(self) -> bool:
        return self.status == "failed"


def build_agent_context(
    *,
    agent_name: str,
    as_of_date: date,
    generated_at: datetime,
    base_currency: str,
    settings: Settings | None = None,
    input_refs: tuple[AgentInputRef, ...] = (),
    report_history: tuple[ReportHistoryEntry, ...] = (),
    metadata: Mapping[str, Any] | None = None,
    run_id: str | None = None,
) -> AgentContext:
    """Build a common agent context with an auto-generated run id."""
    resolved_settings = get_settings() if settings is None else settings
    return AgentContext(
        agent_name=agent_name,
        run_id=uuid4().hex if run_id is None else run_id,
        as_of_date=as_of_date,
        generated_at=generated_at,
        base_currency=base_currency,
        settings=resolved_settings,
        input_refs=input_refs,
        report_history=report_history,
        metadata={} if metadata is None else metadata,
    )
