"""Reusable application use cases for scripts, Streamlit, and future UIs."""

from src.application.degiro import ImportDegiroRequest, ImportDegiroResult, ImportDegiroUseCase
from src.application.market_data import (
    FxRequirementView,
    InferFxRequirementsRequest,
    InferFxRequirementsResult,
    InferFxRequirementsUseCase,
    RefreshFxRequest,
    RefreshFxResult,
    RefreshFxUseCase,
    RefreshMarketDataRequest,
    RefreshMarketDataResult,
    RefreshMarketDataUseCase,
)
from src.application.uploads import (
    DegiroUpload,
    DegiroUploadOutcome,
    SaveDegiroUploadsRequest,
    SaveDegiroUploadsResult,
    SaveDegiroUploadsUseCase,
)
from src.application.agents import RunMonthlyAgentsRequest, RunMonthlyAgentsResult, RunMonthlyAgentsUseCase
from src.application.agent_audit import (
    AgentRunSummary,
    GetAgentRunAuditRequest,
    GetAgentRunAuditResult,
    GetAgentRunAuditUseCase,
    ListAgentRunsResult,
    ListAgentRunsUseCase,
)
from src.application.quality_checks import (
    RunAgentQualityChecksRequest,
    RunAgentQualityChecksResult,
    RunAgentQualityChecksUseCase,
)
from src.application.reports import (
    GenerateMonthlyReportRequest,
    GenerateMonthlyReportResult,
    GenerateMonthlyReportUseCase,
    GetLatestMonthlyReportResult,
    GetLatestMonthlyReportUseCase,
)
from src.application.dashboard import (
    BuildAgentDashboardSnapshotRequest,
    BuildAgentDashboardSnapshotResult,
    BuildAgentDashboardSnapshotUseCase,
    GetNetExternalContributionsRequest,
    GetNetExternalContributionsResult,
    GetNetExternalContributionsUseCase,
    GetPendingDegiroImportStatusResult,
    GetPendingDegiroImportStatusUseCase,
    GetWarehouseCountsResult,
    GetWarehouseCountsUseCase,
    ListDashboardReportsResult,
    ListDashboardReportsUseCase,
    LoadPortfolioMetricsRequest,
    LoadPortfolioMetricsResult,
    LoadPortfolioMetricsUseCase,
    LoadPortfolioSnapshotsResult,
    LoadPortfolioSnapshotsUseCase,
    LoadPortfolioTransactionsResult,
    LoadPortfolioTransactionsUseCase,
    ReadTargetWeightsResult,
    ReadTargetWeightsUseCase,
    extract_monthly_report_as_of_date,
    extract_report_as_of_date_from_path,
    net_external_contributions_until,
)
from src.application.settings import (
    ReadInvestmentBriefResult,
    ReadInvestmentBriefUseCase,
    UpdateInvestmentBriefRequest,
    UpdateInvestmentBriefResult,
    UpdateInvestmentBriefUseCase,
)
from src.application.portfolio_targets import (
    DEFAULT_TARGET_WEIGHTS,
    ReadPortfolioTargetsResult,
    ReadPortfolioTargetsUseCase,
    UpdatePortfolioTargetsRequest,
    UpdatePortfolioTargetsResult,
    UpdatePortfolioTargetsUseCase,
)
from src.application.portfolio_state import (
    GetPortfolioStateRequest,
    GetPortfolioStateResult,
    GetPortfolioStateUseCase,
)
from src.application.contribution_lab import (
    SimulateContributionRequest,
    SimulateContributionResult,
    SimulateContributionUseCase,
)
from src.application.monitor import (
    RunMonitorTematicoRequest,
    RunMonitorTematicoResult,
    RunMonitorTematicoUseCase,
)
from src.application.types import ApplicationResult, ApplicationStatus

__all__ = [
    "ApplicationResult",
    "ApplicationStatus",
    "AgentRunSummary",
    "DEFAULT_TARGET_WEIGHTS",
    "GenerateMonthlyReportRequest",
    "GenerateMonthlyReportResult",
    "GenerateMonthlyReportUseCase",
    "GetAgentRunAuditRequest",
    "GetAgentRunAuditResult",
    "GetAgentRunAuditUseCase",
    "BuildAgentDashboardSnapshotRequest",
    "BuildAgentDashboardSnapshotResult",
    "BuildAgentDashboardSnapshotUseCase",
    "GetNetExternalContributionsRequest",
    "GetNetExternalContributionsResult",
    "GetNetExternalContributionsUseCase",
    "GetPendingDegiroImportStatusResult",
    "GetPendingDegiroImportStatusUseCase",
    "GetPortfolioStateRequest",
    "GetPortfolioStateResult",
    "GetPortfolioStateUseCase",
    "GetWarehouseCountsResult",
    "GetWarehouseCountsUseCase",
    "FxRequirementView",
    "InferFxRequirementsRequest",
    "InferFxRequirementsResult",
    "InferFxRequirementsUseCase",
    "GetLatestMonthlyReportResult",
    "GetLatestMonthlyReportUseCase",
    "ImportDegiroRequest",
    "ImportDegiroResult",
    "ImportDegiroUseCase",
    "ListAgentRunsResult",
    "ListAgentRunsUseCase",
    "ListDashboardReportsResult",
    "ListDashboardReportsUseCase",
    "LoadPortfolioMetricsRequest",
    "LoadPortfolioMetricsResult",
    "LoadPortfolioMetricsUseCase",
    "LoadPortfolioSnapshotsResult",
    "LoadPortfolioSnapshotsUseCase",
    "LoadPortfolioTransactionsResult",
    "LoadPortfolioTransactionsUseCase",
    "RefreshFxRequest",
    "RefreshFxResult",
    "RefreshFxUseCase",
    "RefreshMarketDataRequest",
    "RefreshMarketDataResult",
    "RefreshMarketDataUseCase",
    "ReadInvestmentBriefResult",
    "ReadInvestmentBriefUseCase",
    "ReadPortfolioTargetsResult",
    "ReadPortfolioTargetsUseCase",
    "ReadTargetWeightsResult",
    "ReadTargetWeightsUseCase",
    "UpdateInvestmentBriefRequest",
    "UpdateInvestmentBriefResult",
    "UpdateInvestmentBriefUseCase",
    "UpdatePortfolioTargetsRequest",
    "UpdatePortfolioTargetsResult",
    "UpdatePortfolioTargetsUseCase",
    "RunMonthlyAgentsRequest",
    "RunMonthlyAgentsResult",
    "RunMonthlyAgentsUseCase",
    "RunMonitorTematicoRequest",
    "RunMonitorTematicoResult",
    "RunMonitorTematicoUseCase",
    "RunAgentQualityChecksRequest",
    "RunAgentQualityChecksResult",
    "RunAgentQualityChecksUseCase",
    "DegiroUpload",
    "DegiroUploadOutcome",
    "SaveDegiroUploadsRequest",
    "SaveDegiroUploadsResult",
    "SaveDegiroUploadsUseCase",
    "SimulateContributionRequest",
    "SimulateContributionResult",
    "SimulateContributionUseCase",
    "extract_report_as_of_date_from_path",
    "extract_monthly_report_as_of_date",
    "net_external_contributions_until",
]
